# Here are all variables you may need for the messages:
# &0 - Black          &6 - Gold          &c - Red
# &1 - Dark Blue      &7 - Gray          &d - Light Purple
# &2 - Dark Green     &8 - Dark Gray     &e - Yellow
# &3 - Dark Aqua      &9 - Blue          &f - White
# &4 - Dark Red       &a - Green         &bold - Bold
# &5 - Dark Purple    &b - Aqua          &italic - Italic
# &strike - Striked   &under - Underline &magic - Magic       &reset - Reset
# %NAME  - %IP  - %WORLD  - %GAMEMODE  - %ONLINEPLAYERS  - %MAXPLAYERS
# %ONLINELIST  - %SERVERNAME   (OnlinePlayers gives a number, OnlineList all the names.)

########## Important Rule for the config.yml! ##########
# Whenever there is a configurable message sent to someone, surround that part with these! ' '
########## Important Rule for the config.yml! ##########



# Enable the plugin?
enable: true
# Automatically check for updates?
CheckUpdate: true
# Log usage of commands to console?
logToConsole: true

# Do you want player modifications (name,allowFly,...) to be reset
# when the player logs out and back in? Separate with ';'
# All modifications not specified here will be re-enabled, depending on the information in the PlayerLog.yml file.
# Fly: Reset allowing/denying to fly.
# Name: Reset the player's name.
# Hidden: Show the player again.
# Muted: Allow the player to speak if he/she has been muted.
# Example: Fly;Hidden
reset: Fly;Hidden


# Do you want custom join/quit messages?
customJQ: true
# Set your join message here.
joinMsg: '&aHello %NAME!'
# This is the message other players will see.
joinMsgOther: '&bPlayer &e%NAME &b(&c%IP&b) has connected.'
# The quit message when somebody leaves your server.
quitMsg: '&e%NAME has left the game.'
# The message a muted player is shown when he tries to chat.
mutedMsg: '&cYou have been muted.'


# Define the order of the information shown on /pinfo here. Separate the words with ';'
# Name: The player's name
# PlayedTime: The time the player has been playing on your server.
# IP: The player's IP address
# FirstLogin: The date and time the player has been seen for the first time.
# LastLogin: The date and time the player has joined the last time.
# LastLogout: The date and time the player has left the last time.
# Money: The amount of money a player has. Vault is REQUIRED.
# Group: The primary group the player is in. Vault is REQUIRED.
# World: The world the player is in
# Health: The player's health
# Food: The player's food level
# Xp: The player's Xp level
# GameMode: The player's gamemode
# Position: The player's position
# Distance: The distance from the command executor to the player
# AllowFlight: Whether the player is allowed to fly or not.
# Hidden: Whether the player is hidden or not.
# Muted: Whether the player is muted or not.
# Rules: Whether the player has read and accepted the rules or not.
# Example: Name;FirstLogin;PlayedTime;IP;World;Xp;Muted
order: Name;FistLogin;PlayedTime;IP;World;Xp;Muted


# Players who are fakeops themselves or do not have permission to use
# the fakeop-related commands trying to use them will receive this message.
fakeOpNoPerm: '&fUnknown command. Type "help" for help.'
# This message is sent to people who get fake-opped.
fakeOpYes: '&eYou are now op!'
# This message is sent to people who lose the fakeop status.
fakeOpNo: '&eYou are no longer op!'
# This is what happens when a fakeop tries to do something. 
# Broadcast: Instead of executing a command, it is sent to the chat. Everyone can see it except the fakeop. If you want to use a white- or blacklist, put [Whitelist] or [Blacklist] behind Broadcast!
# DontKnow: No matter what command he types, he will always receive "Unknown command. Type "help" for help."
# GoHelp[]: If he tries to break a block, he will be sent the message between the square brackets and the block will reappear.
# Mute: The fakeop will be muted, but he won't know... He's going to think that everyone's ignoring him! PlayerManager needs the Chat-Prefix in curly brackets.
# Example: Broadcast[Whitelist];GoHelp['&cYou are op! Now go help someone!'];Mute{'<&2[Member]&f %NAME> '}
fakeOpAnnoy: DontKnow;GoHelp['You are op. Go and help someone!']
# This is the Broadcast white/blacklist. All commands listed here WILL NOT be sent (whitelist) or WILL be sent (blacklist) to the chat instead of being executed.
fakeList:
    - /help
    - /plugins
    - /version
    - /rules


# Should the /rules and /acceptrules commands be enabled?
enableRules: true
# This option determines the commands which are executed when someone types /acceptrules
# Separate the commands with '|' and separate the arguments with spaces.
# The % Variables can be used here, i.e. %NAME, &IP, %WORLD...
# Example: give %NAME stone_sword 1|say WELCOME %NAME TO THE SERVER!
RulesExCmd: 'give %NAME stone_sword 1|say WELCOME %NAME TO THE SERVER!'
# Write your rules here. It does not matter how long they are, just make sure to
# always increase the Rules[number] by one. You can have Rules1 - Rules5832, but not Rules2 - Rules4!
# Each of those Rules[number] will be written on a new line.
# %VARIABLE will give server information. Don't use %NAME, %WORLD and %GAMEMODE.
Rules1: '&3---- &bold%SERVERNAME Rules&reset ----'
Rules2: '&1[1] &cDo not grief.'
Rules3: '&1[2] &cBe polite.'
Rules4: '&1[3] &aHave fun :D'

# Prevent players who have not accepted the rules yet from doing the following actions.
# As always, separate those actions with ';'
# BlockBreak: Prevent them from breaking blocks.
# BlockPlace: Prevent them from placing blocks.
# Chat: Prevent them from chatting.
# Chest: Prevent them from opening chests.
# DamageSelf: Prevent them from being hurt by mobs or other players.
# DamageOthers: Prevent them from hurting any other player or mob.
# Move[]: Keep them in a defined radius from the spawn point.
# PickUpDrops: Don't let them pick up any items.
# Redstone: Prevent them from using levers, buttons or pressure plates.
# Example: Move[10];DamageOthers;PickUpDrops;BlockBreak;BlockPlace
PreventNotAccepted: 'Move[10];DamageOthers;PickUpDrops;BlockBreak;BlockPlace'
# This is a command whitelist. Only the commands specified here will be allowed to players who haven't accepted the rules.
RulesWhiteList:
    - rules
    - acceptrules
    - login
    - register
# This is the message your players will be shown if they try to do anything you've specified above, except picking up drops.
RulesNotAcceptedMsg: '&cYou are not allowed to do this until you accepted the server rules! Type &2/acceptrules&c!'
# This is the message a player will be shown when he tries to damage a player who has not accepted the rules yet.
# This only has an effect if you included DamageSelf above.
RulesNotAcceptedDmgSelfMsg: '&eThis player has not accepted the rules yet. Let him live until then ;)'
# This is the message a player will be shown if he tries to execute a command that's not on the whitelist.
RulesNotAcceptedWLMsg: '&eYou are not allowed to execute this command until you accepted the rules.'

# Enable teleporting when typing /acceptrules for the first time?
RulesTeleport: false
# The position they will be teleported to. Change this in-game by typing /pman srtp.
RulesTpWorld: world
RulesTpX: 0.0
RulesTpY: 64.0
RulesTpZ: 0.0
RulesTpPitch: 0.0
RulesTpYaw: 0.0


# Enable the /report and /check commands?
EnableReport: true
# After how many /reports do you want configurable commands to be executed? -1 disables.
ReportCmd: 3
# What commands should be executed? Separate them using |, %VARIABLE are allowed to be used.
# Example: 'say %NAME watch out what you are doing...|pman set weather storm'
ReportEXCmd: 'say %NAME watch out what you are doing... you have been reported three times.'
# After how many /reports do you want the player to be kicked? -1 disables.
ReportKick: 5
# The message a kicked player will be shown. Do not use any variables.
ReportKickMsg: 'You have been reported too often. You should behave better.'
# After how many /reports do you want the player to be banned? -1 disables.
ReportBan: 7
# The message a banned player will be shown. Do not use any variables.
ReportBanMsg: 'Too many reports. You have been warned.'
# What banning method should be used? This should be either name, ip or both.
ReportBanMethod: ip
# The cooldown in seconds for the /report command. -1 disables.
ReportCoolDown: 30
# The message a player will be shown when he tries to use the command but the cooldown has not finished yet.
ReportCoolDownMsg: '&6This command is not ready yet!'


# Enable the censorship of bad words?
EnableCensor: true
# Which words shall be censored? Only use lowercases!
CensorWords:
    - fuck
    - shit
    - bitch
# Select the character with which the bad words shall be replaced.
CensorChar: '*'


# Should BotBlocking be enabled?
# Not recommended. It's old and buggy code, I will do that better soon,
# depending on the result of the poll I created on the page where you downloaded my plugin.
#######  http://dev.bukkit.org/server-mods/playermanager  #######
enableBotBlock: false
# Should two players with the same IP be logged in a separated file?
logDuplicatedIps: false
# What should I do if I find two players with
# the same IP? (Normally one of them is a bot then)
# Accepted are kick/ban/none.
punishment: kick


# Should Rei's Minimap be supported? Separate tags with ';'
# false: Disables. If used in combination with other tags, the minimap still won't be supported.
# Cave: Allows cave mapping.
# Player: Allows view of position of a player.
# Animal: Allows view of animals.
# Mob: Allows view of hostile mobs.
# Slime: Allows view of slimes.
# Squid: Allows view of squids.
# Other: Allows view of other living, i.e. golems.
# Example: Player;Mob;Other
supportReiMinimap: false


# DO NOT CHANGE THIS!
version: 7
