name: PlayerManager
main: com.github.Mephilis7.PlayerManager.PMan_main
version: 1.8
author: Mephilis7
softdepend: [Vault]
commands:
  fakeop:
    description: Fake-op a player.
    usage: <command> {player}
    permission: pman.fakeop
  fakedeop:
    description: Remove fakeop status from a player.
    usage: <command> {player}
    permission: pman.fakedeop
  fakelist:
    description: List all (fake-)opped players.
    aliases: oplist
    usage: <command>
    permission: pman.fakelist
  report:
    description: Report a player to the Admins.
    usage: <command> {player}
    permission: pman.report
  check:
    description: Check the current /report state of a player.
    usage: <command> {player} <Number>
    permission: pman.check
  checktp:
    description: Teleport to the location where a report has been sent.
    usage: <command> {player} {Number}
    permission: pman.checktp
  apologise:
    description: Delete a report of a player.
    usage: <command> {player} {Number}
    permission: pman.apologise
  rules:
    description: Prints the rules.
    usage: <command>
    permission: pman.rules
  acceptrules:
    description: Accepts the server rules.
    usage: <command>
    permission: pman.rules
  pman:
    description: Helps you managing your players.
    usage: 'Type /pman for help.'
permissions:
  pman.censor.add:
    description: Allows usage of /pman censor add
    default: op
  pman.censor.delete:
    description: Allows usage of /pman censor delete
    default: op
  pman.censor.disable:
    description: Allows usage of /pman censor disable
    default: op
  pman.censor.enable:
    description: Allows usage of /pman censor enable
    default: op
  pman.censor.list:
    description: Allows usage of /pman censor list
    default: op
  pman.fakeop:
    description: Allows usage of /fakeop
    default: op
  pman.fakedeop:
    description: Allows usage of /fakedeop
    default: op
  pman.fakelist:
    description: Allows usage of /fakelist
    default: op
  pman.help:
    description: Allows usage of /pman
    default: op
  pman.hide:
    description: Allows usage of /pman hide and /pman show
    default: op
  pman.info:
    description: Grants access to /pman info
    default: op
  pman.info.name:
    description: Allows showing Name on /pman info
    default: op
  pman.info.time:
    description: Allows showin played time on /pman info
    default: op
  pman.info.ip:
    description: Allows showing IP address on /pman info
    default: op
  pman.info.firstLogin:
    description: Allows showing the first login on /pman info
    default: op
  pman.info.lastLogin:
    description: Allows showing the last login on /pman info
    default: op
  pman.info.lastLogout:
    description: Allows showing the last logout on /pman info
    default: op
  pman.info.world:
    description: Allows showing World on /pman info
    default: op
  pman.info.money:
    description: Allows showing Money on /pman info
    default: op
  pman.info.group:
    description: Allows showing Groups on /pman info
    default: op
  pman.info.health:
    description: Allows showing Health on /pman info
    default: op
  pman.info.food:
    description: Allows showing FoodLevel on /pman info
    default: op
  pman.info.xp:
    description: Allows showing ExpLevel on /pman info
    default: op
  pman.info.gamemode:
    description: Allows showing GameMode on /pman info
    default: op
  pman.info.position:
    description: Allows showing Position on /pman info
    default: op
  pman.info.distance:
    description: Allows showing distance from target to command executor on /pman info
    default: op
  pman.info.allowFlight:
    description: Allows showing whether the target is allowed to fly or not.
    default: op
  pman.info.hidden:
    description: Allows showing whether the target is hidden
    default: op
  pman.info.mute:
    description: Allows showing whether the target is muted
    default: op
  pman.info.rules:
    description: Allows showing whether the target has accepted the /rules
    default: op
  pman.list:
    description: Allows usage of /pman list
    default: op
  pman.mute:
    description: Allows usage of /pman mute
    default: op
  pman.rules:
    description: Allows usage of /rules and /acceptrules
    default: true
  pman.rulestp:
    description: Allows usage of /pman srtp
    default: op
  pman.set.fly:
    description: Allows setting of AllowFlight
    default: op
  pman.set.food:
    description: Allows setting of food level
    default: op
  pman.set.health:
    description: Allows setting of health
    default: op
  pman.set.name:
    description: Allows setting of name
    default: op
  pman.set.weather:
    description: Allows setting of the weather.
    default: op
  pman.set.xp:
    description: Allows setting of xp level
    default: op
  pman.report:
    description: Allows usage of /report
    default: true
  pman.check: 
    description: Check the /report state of a player.
    default: op
  pman.checktp:
    description: Teleport to a location where /report had been typed.
    default: op
  pman.apologise:
    description: Allows usage of /apologise
    default: op
  pman.reload:
    description: Allows usage of /pman reload
    default: op
  pman.update:
    description: Notifies when joining the server and an update is out.
    default: op
  pman.view:
    description: Allows to you view hidden players.
    default: op