name: PlayerManager
main: com.github.Mephilis7.PlayerManager.PMan_main
version: 1.3_Beta1
author: Mephilis7
commands:
  pman:
    description: Helps you managing your players.
    usage: 'Type /pman for help.'
permissions:
  pman.help:
    description: Allows usage of /pman
    default: op
  pman.info:
    description: Grants access to /pman info
    default:op
  pman.info.name:
    description: Allows showing Name on /pman info
    default: op
  pman.info.ip:
    description: Allows showing IP address on /pman info
    default: op
  pman.info.world:
    description: Allows showing World on /pman info
    default: op
  pman.info.health:
    description: Allows showing Health on /pman info
    default: op
  pman.info.food:
    description: Allows showing FoodLevel on /pman info
    default: op
  pman.info.xp:
    description: Allows showing ExpLevel on /pman info
    default: op
  pman.info.gamemode:
    description: Allows showing GameMode on /pman info
    default: op
  pman.info.position:
    description: Allows showing Position on /pman info
    default: op
  pman.info.distance:
    description: Allows showing distance from target to command executor on /pman info
    default: op
  pman.list:
    description: Allows usage of /pman list
    default: op
  pman.reload:
    description: Allows usage of /pman reload
    default: op